knife4j:
  enable: true
  setting:
    enable-footer: false
    enable-document-manage: false
    enable-reload-cache-parameter: true
  openapi:
    title: 微观纪元项目管理系统
    description: ${knife4j.openapi.title}
    version: v1.0
    concat: dongjingxiang
    email: dongjingxiang@miqroera.com
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.era.miqroproject.app.api.common
          - com.era.miqroproject.app.api.portal
      manage:
        api-rule: package
        api-rule-resources:
          - com.era.miqroproject.app.api.common
          - com.era.miqroproject.app.api.manage
  production: false